name: Test Package

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: 'Test on Node.js ${{ matrix.node-version }} (${{ matrix.os }})'

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16, 18, 20]

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Test package installation
        run: |
          # Test that the package can be packed
          npm pack --dry-run

          # Test basic import
          node -e "
            const AgentOrchestrator = require('./equilateral-core/AgentOrchestrator');
            const BaseAgent = require('./equilateral-core/BaseAgent');
            const CodeAnalyzer = require('./agent-packs/development/CodeAnalyzerAgent');
            console.log('✅ All core modules can be imported');
          "

      - name: Test demo (without AI)
        run: |
          # Run a basic test without AI dependencies
          node -e "
            const AgentOrchestrator = require('./equilateral-core/AgentOrchestrator');
            const orchestrator = new AgentOrchestrator();
            console.log('✅ AgentOrchestrator can be instantiated');
          "